name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: SreenivasSTOP
      url: https://staging.example.com
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Deploying to STAGING..."
          echo "Using secret: ${{ secrets.STAGING_API_KEY }}"

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://prod.example.com
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "Deploying to PRODUCTION..."
          echo "Using secret: ${{ secrets.PROD_API_KEY }}"
